services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    ports:
      - "80:80"

  php:
    image: php:8.4-fpm
    volumes:
      - ./:/var/www/html
# depends_on:
#   - php
# stdin_open: true
# tty: true
