services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./images/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - "8000:80"

  php:
    # image: php:8.4-fpm-alpine
    build:
      context: .
      dockerfile: ./images/php/Dockerfile
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"

volumes:
  dbdata:

# depends_on:
#   - php
# stdin_open: true
# tty: true
