services:
  web:
    image: nginx:stable-alpine
    volumes:
      - ./images/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    ports:
      - "8000:80"

  php:
    image: php:8.4-fpm-alpine
    volumes:
      - ./app:/var/www/html
# depends_on:
#   - php
# stdin_open: true
# tty: true
